USE [master]
GO

/****** Object:  Database [PSS_ElliottMarketing]    Script Date: 8/8/2019 9:50:48 AM ******/
CREATE DATABASE [PSS_ElliottMarketing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PSS_ElliottMarketing_Data', FILENAME = N'E:\ElliottMarketing\PSS_ElliottMarketing.mdf' , SIZE = 8295808KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'PSS_ElliottMarketing_log', FILENAME = N'E:\ElliottMarketing\PSS_ElliottMarketing_log.ldf' , SIZE = 411008KB , MAXSIZE = 2048GB , FILEGROWTH = 102400KB )
GO

ALTER DATABASE [PSS_ElliottMarketing] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PSS_ElliottMarketing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PSS_ElliottMarketing] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET ARITHABORT OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET  MULTI_USER 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PSS_ElliottMarketing] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PSS_ElliottMarketing] SET QUERY_STORE = OFF
GO

USE [PSS_ElliottMarketing]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PSS_ElliottMarketing] SET  READ_WRITE 
GO


